package routes

// This file is auto-generated by Codl.

import (
	"github.com/Masterminds/cookoo"
	`github.com/Masterminds/codl/cmd`
	
)

func AppRoutes(reg *cookoo.Registry) {
	reg.Route(`build`, `Build all CODL files in the given directory`).
		Does(cmd.FindCodl, `files`).
		Does(cmd.Translate, `created`).
			Using(`files`).From(`cxt:files`)

	
}
