package routes

// This file is auto-generated by Codl.

import (
	"github.com/Masterminds/cookoo"
	`github.com/Masterminds/cookoo/cli`
	`github.com/Masterminds/codl/cmd`
	
)

func AppRoutes(reg *cookoo.Registry) {
	reg.Route(`@update`, `Updates all given CODL files`).
	Does(cmd.Translate, `created`).
			Using(`files`).From(`cxt:files`).
			Using(`skipEmpty`).WithDefault(true)
	reg.Route(`build`, `Build all CODL files in the given directory`).
	Does(cli.ParseArgs, `build.Args`).
			Using(`subcommand`).WithDefault(true).
			Using(`args`).From(`cxt:runner.Args`).
			Using(`flagset`).WithDefault(buildFlags).
	Does(cli.ShowHelp, `help`).
			Using(`show`).From(`cxt:h`).
			Using(`summary`).WithDefault(`Transform CODL files into Go source.`).
			Using(`flags`).WithDefault(buildFlags).
	Does(cmd.FindCodl, `files`).
			Using(`dir`).From(`cxt:d`).
	Does(cmd.Translate, `created`).
			Using(`files`).From(`cxt:files`).
			Using(`skipEmpty`).WithDefault(true)
	reg.Route(`watch`, `Watch all files in a directory for changes.`).
	Does(cli.ParseArgs, `build.Args`).
			Using(`subcommand`).WithDefault(true).
			Using(`args`).From(`cxt:runner.Args`).
			Using(`flagset`).WithDefault(buildFlags).
	Does(cli.ShowHelp, `help`).
			Using(`show`).From(`cxt:h`).
			Using(`summary`).WithDefault(`Watch CODL files and transform them to Go when they are modified.`).
			Using(`flags`).WithDefault(buildFlags).
	Does(cmd.Watch, `watch`).
			Using(`dir`).From(`cxt:d`)
	reg.Route(`version`, `Print version and exit`).
	Does(cmd.Version, `ver`).
			Using(`version`).From(`cxt:version`)
	
}
