package parser

import (
	"github.com/Masterminds/sprig"
	"io"
	"text/template"
)

const bodyTpl = `package {{.Package}}

// This file is auto-generated by Codl.

import (
	"github.com/Masterminds/cookoo"
	{{range .Registry.Imports}}{{.}}
	{{end}}
)

func {{.Name | title }}Routes(reg *cookoo.Registry) {
	{{range .Registry.Routes}}reg.Route({{.Name}}, {{.Description}}){{range .Commands}}.
		Does({{.Cmd}}, {{.Name}}){{range .Params}}.
			Using({{.Name}}){{if .DefaultVal}}.WithDefault({{.DefaultVal}}){{end}}{{if .From}}.From({{.From | join ", "}}){{end}}{{end}}{{end}}

	{{end}}
}
`

type Registry interface {
	Routes() []*Route
	Imports() []string
}

type serializerContext struct {
	Registry Registry
	Package string
	Name string
}

type Serializer struct {
	out io.Writer
	reg Registry
	tpl *template.Template
	name string
}

func NewSerializer(name string, out io.Writer, reg Registry) *Serializer {
	s := &Serializer{name: name, out: out, reg: reg}
	s.compile()

	return s
}

func (s *Serializer) Write() error {
	cxt := &serializerContext {
		Name: s.name,
		Registry: s.reg,
		Package: "routes",
	}
	return s.tpl.Execute(s.out, cxt)
}

func (s *Serializer) compile() {
	s.tpl = template.Must(template.New("body").Funcs(sprig.TxtFuncMap()).Parse(bodyTpl))
}

